### ISSUE TITLE
WebSockets server socket closing itself?

### ISSUE THREAD

**Issue by abbihors** [probable-basilisk/pollnet#6]
I'm having some issues trying to use websockets with pollnet. So here I've got a simple echo server:

```lua
local pollnet = require("pollnet") 

local sock = pollnet.listen_ws("ws://127.0.0.1:12347")

while true do
  if not sock then return end

  local happy, msg = sock:poll()
  
  if not happy then
    print("closing sock")
    sock:close() -- good form to avoid keeping listen_sockets open
    sock = nil
    os.exit()
  else
    print("happy")
  end

  if msg then
    sock:send(msg)
  end
end
```

But this is what it prints:

```
$ ./luajit.exe wsserv.lua
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
happy
closing sock
```

**Comment by probable-basilisk** [comment]
Sorry for the late reply. You should do `pollnet.listen_ws("127.0.0.1:12347")`, without the "ws://". The reason it seems happy to begin with is because the socket is opened on a different thread, so luajit can loop a few times before the message comes back that it wasn't able to open the socket.

You can print out the reason it closes with:
```lua
  if not happy then
    print("closing sock; reason: ", msg)
    sock:close() -- good form to avoid keeping listen_sockets open
    sock = nil
    os.exit()
  else
    print("happy")
  end
 ```
 
You'll get something like "failed to lookup address information: nodename nor servname provided, or not known", which is complaining that "ws://127.0.0.1:12347" is not a valid TCP address (because of the "ws://" in front).
